# Generated by Django 5.1.3 on 2024-11-25 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_passing', '0001_initial'),
        ('users', '0003_alter_student_managers_alter_teacher_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_passing.test')),
            ],
            options={
                'verbose_name': 'Сессия теста',
                'verbose_name_plural': 'Сессии тестов',
                'db_table': 'test_session',
            },
        ),
    ]
