# Generated by Django 5.1.3 on 2024-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_passing', '0002_testsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsession',
            options={},
        ),
        migrations.AddField(
            model_name='testsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='testsession',
            table=None,
        ),
    ]
