# Generated by Django 5.1.3 on 2024-11-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_passing', '0003_alter_testsession_options_testsession_completed_and_more'),
        ('users', '0003_alter_student_managers_alter_teacher_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together={('student', 'test')},
        ),
    ]
